# Generated by Django 5.2.8 on 2026-07-07 21:37

import uuid
from django.db import migrations, models


def deduplicate_organization_uids(apps, schema_editor):
    Organization = apps.get_model("clerk_organizations", "Organization")
    db_alias = schema_editor.connection.alias
    seen_uids = set()

    organizations = (
        Organization.objects.using(db_alias)
        .order_by("uid", "pk")
        .values_list("pk", "uid")
    )
    for organization_pk, organization_uid in organizations.iterator():
        if organization_uid not in seen_uids:
            seen_uids.add(organization_uid)
            continue

        new_uid = uuid.uuid4()
        while new_uid in seen_uids:
            new_uid = uuid.uuid4()

        Organization.objects.using(db_alias).filter(pk=organization_pk).update(
            uid=new_uid
        )
        seen_uids.add(new_uid)


class Migration(migrations.Migration):
    dependencies = [
        ("clerk_organizations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="organization",
            name="clerk_organ_clerk_i_b2b811_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="clerk_organ_slug_6c2124_idx",
        ),
        migrations.RemoveIndex(
            model_name="organization",
            name="clerk_organ_is_acti_67b48f_idx",
        ),
        migrations.RunPython(
            deduplicate_organization_uids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="organization",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Public unique identifier for the organization.",
                unique=True,
            ),
        ),
    ]
