# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_clerk_users", "0003_add_username_make_email_nullable"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddIndex(
                    model_name="clerkuser",
                    index=models.Index(
                        fields=["username"], name="django_cler_usernam_323ad9_idx"
                    ),
                ),
            ],
        ),
    ]
