# Generated by Django 5.2.8 on 2026-07-07 21:37

import uuid
from django.db import migrations, models


def deduplicate_clerkuser_uids(apps, schema_editor):
    ClerkUser = apps.get_model("django_clerk_users", "ClerkUser")
    db_alias = schema_editor.connection.alias
    seen_uids = set()

    users = (
        ClerkUser.objects.using(db_alias).order_by("uid", "pk").values_list("pk", "uid")
    )
    for user_pk, user_uid in users.iterator():
        if user_uid not in seen_uids:
            seen_uids.add(user_uid)
            continue

        new_uid = uuid.uuid4()
        while new_uid in seen_uids:
            new_uid = uuid.uuid4()

        ClerkUser.objects.using(db_alias).filter(pk=user_pk).update(uid=new_uid)
        seen_uids.add(new_uid)


class Migration(migrations.Migration):
    dependencies = [
        ("django_clerk_users", "0004_clerkuser_username_index_state"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clerkuser",
            name="django_cler_clerk_i_d591b6_idx",
        ),
        migrations.RemoveIndex(
            model_name="clerkuser",
            name="django_cler_email_f1e649_idx",
        ),
        migrations.RemoveIndex(
            model_name="clerkuser",
            name="django_cler_uid_9f6a95_idx",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="clerkuser",
                    name="django_cler_usernam_323ad9_idx",
                ),
            ],
        ),
        migrations.RunPython(
            deduplicate_clerkuser_uids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="clerkuser",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Public unique identifier for the user.",
                unique=True,
            ),
        ),
    ]
