name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  tests:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        python-version:
        - '3.12'
        - '3.13'
        - '3.14'

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: uv.lock

    - name: Install dependencies
      run: uv pip install --system tox tox-uv

    - name: Run tox targets for ${{ matrix.python-version }}
      run: tox run -f py$(echo ${{ matrix.python-version }} | tr -d .)

  release:
    needs: [tests]
    runs-on: ubuntu-24.04
    environment: release

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4

      - name: Build
        run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
